intmap \
  -ltr_reads data/sample3_R1.fq.gz \
  -linker_reads data/sample3_R2.fq.gz \
  -ltr AGGAACCCCTAGTGATGGAGTTGGCCACTCCCTCTCTGCGCGCTCGCTCGCTCACTGAGGCCGGGCGACCAAAGGTCGCCCGACGCCCGGGCTTTGCCCGGGCGGCCTCAGTGAGCGAGCGAGCGCGCAGAGAGGGAGTGGCCAA \
  -ltr2 AGGAACCCCTAGTGATGGAGTTGGCCACTCCCTCTCTGCGCGCTCGCTCGCTCACTGAGGCGCCCGGGCGAAACGCCCGGGCTGGTCGCCCGTTTCGGGCGACCGCCTCAGTGAGCGAGCGAGCGCGCAGAGAGGGAGTGGCCAA \
  -linker ATGAGCATTCTACACGATTAC \
  -nm truncated_example \
  -nthr 4 \
  -g_idx_dir /Users/gbedwell/Documents/github/T2T_genome/indexes/bowtie2 \
  -g_idx_name hs1 \
  -v_idx_dir /Users/gbedwell/Documents/github/virus_genomes/HIV-1 \
  -v_idx_name hiv1 \
  -linker_umi_offset 0 \
  -linker_umi_len 12 \
  -seq_sim 1 \
  -len_diff 0 \
  -frag_ratio 1000 \
  -min_count 1000 \
  -abundant_fc 1000 \
  --reassign_mm \
  --ttr > outputs/truncated_output.txt