#!/usr/bin/env python3
import os
import glob
import sys
import gzip
import math
import glob
import shutil
import subprocess
from intmap import crop
from intmap import align
from intmap import process
from intmap import clean
from intmap.utils import *
import pysam
import time
from collections import defaultdict
import json
from joblib import Parallel, delayed
import pyranges as pr
import pandas as pd
import parasail
import argparse

parser = argparse.ArgumentParser(prog='intmap',
                                 description='''Maps the locations of genomic integration sites from NGS data.''')
parser.add_argument('-ltr_reads',
                    type=str, 
                    help='''The path to integrant-end reads. 
                    Expects the defined integrant sequence to be near the 5\' end of the read.''',
                    default=None, 
                    required=True)
parser.add_argument('-linker_reads',
                    type=str,
                    help='''The path to linker-end reads or non-integrant-end (i.e., the mate to ltr_reads). 
                    Should contain the defined linker sequence near the 5\' end of the read. 
                    Only used with paired-end data.''', 
                    default=None, 
                    required=False)
parser.add_argument('-ltr',
                    type=str, 
                    help='''The LTR (or integrant) sequence to match. 
                    Must be given in 5\' to 3\' orientation.
                    Must be at least 10 nt long.''', 
                    default=None,
                    required=False)
parser.add_argument('-ltr2',
                    type=str, 
                    help='''An alternative orientation of the LTR/integrant search-sequence. 
                    Used for e.g., distinguishing between flip and flop orientations of AAV ITRs.''', 
                    default=None)
parser.add_argument('-linker',
                    type=str, 
                    help='''The linker sequence to match. 
                    Required for paired-end and long-read data. 
                    Must be given in the 5\' to 3\' orientation, 
                    even when sequenced in the 3\' to 5\' orientation 
                    on the 3\' end of ltr_reads (e.g., in long-read data). 
                    Must be at least 10 nt long.''', 
                    default=None)
parser.add_argument('-ltr_error_rate',
                    type=float, 
                    help='''The acceptable error rate in the LTR sequence. 
                    Defaults to 0.1. Cannot exceed 0.4.''',
                    default=0.1)
parser.add_argument('-linker_error_rate',
                    type=float, 
                    help='''The acceptable error rate in the linker sequence.
                    Defaults to 0.1. Cannot exceed 0.4.''',
                    default=0.1)
parser.add_argument('-contam',
                    type=str, 
                    nargs='*', 
                    help='''Possible contaminating sequences immediately downstream of the defined integrant search sequence.''', 
                    default=None)
parser.add_argument('-ltr_primer',
                    type=str,  
                    help='''The 3' end of the integrant primer used for PCR amplification. 
                    Used to control for mispriming during fragment amplification. 
                    Must be at least 10 bp.''',
                    default=None)
parser.add_argument('--U3', '-U3',
                    help='''Whether or not the integrant-host junctions are sequenced from the U3 end of the provirus (or equivalent). 
                    This should be set for any sequencing strategy that sequences the integrant off of the reverse strand. Used for defining the 
                    1st bp of the target site duplication (when applicable), properly defining integrant orientation, etc.''',
                    action='store_true')
parser.add_argument('-nthr',
                    type=int, 
                    help='The number of threads to use for processing.',
                    default=1)
parser.add_argument('-nm',
                    type=str, 
                    help='''The name of the dataset. 
                    This is used for naming output files.''',
                    required=True)
parser.add_argument('--ttr', '-ttr', '--truncated_terminal_repeat', '-truncated_terminal_repeat',
                    help='''Tells the software to look for truncation of the defined integrant search sequence. When set/True, the first min_ttr_len bases of the 
                    search sequence are assumed to be obligatory (an anchor sequence).''',
                    action='store_true')
parser.add_argument('-min_ttr_len',
                    type=int,
                    help='''The minimum allowed length of the truncated terminal repeat. 
                    Only used with ttr is True. 
                    Defaults to 10.''',
                    default=10)
parser.add_argument('--cap_ttr_error', '-cap_ttr_error',
                    help='''When set/True, the number of mismatches allowed for truncated integrant ends is capped at min_ttr_len * ltr_error_rate.''',
                    action='store_true')
parser.add_argument('--leftmost', '-leftmost',
                    help='''When set/True, cutadapt looks for the leftmost occurrence of the defined LTR/integrant 
                    search sequence. When not set/False (default), the rightmost occurrence is found. 
                    Does not affect linker search sequencing position.''',
                    action='store_true')
parser.add_argument('--mixed', '-mixed',
                    help='''When set/True, the cropping step accomodates situations where library preparation 
                    can result in target integrant-ends on either terminus of a given fragment.
                    Cannot be used with single-end short-read data.''',
                    action='store_true')
parser.add_argument('-min_frag_len',
                    type=int, 
                    help='''The minimum allowed fragment length. 
                    Defaults to 25.''',
                    default=25)
parser.add_argument('-max_frag_len',
                    type=int, 
                    help='''The maximum allowed fragment length. 
                    Defaults to 2000.''',
                    default=2000)
parser.add_argument('-bed_path',
                    type=str, 
                    help='The path to the bedtools executable. OK to ignore for standard installations.',
                    default='bedtools')
parser.add_argument('-mm2_path',
                    type=str, 
                    help='The path to the minimap2 executable. OK to ignore for standard installations.',
                    default='minimap2')
parser.add_argument('-g_idx_dir',
                    type=str, 
                    help='''The path to the Bowtie2 or minimap2 genome index directory.
                    Note that this should not contain the index prefix.''',
                    default=None)
parser.add_argument('-g_idx_name',
                    type=str, 
                    help='''The genome index prefix (e.g., hs1).''',
                    default=None)
parser.add_argument('-v_idx_dir',
                    type=str, 
                    help='''The path to the virus genome index directory. 
                    Note that this should not contain the index prefix.''',
                    default=None)
parser.add_argument('-v_idx_name',
                    type=str, 
                    help='''The virus genome index prefix.''',
                    default=None)
parser.add_argument('-aln_mismatch_rate',
                    type=float, 
                    help='''The allowable mismatch rate in read alignment.
                    N's and soft-clipped bases are counted as mismatches.
                    Defaults to 0.10.''',
                    default=0.10)
parser.add_argument('-aln_indel_rate',
                    type=float, 
                    help='''The allowable indel rate in read alignment. 
                    Defaults to 0.02.''',
                    default=0.02)
parser.add_argument('-min_mapq',
                    type=int, 
                    help='''The minimum acceptable MAPQ score.
                    Does not apply to multimapping reads. 
                    Defaults to 2.''',
                    default=2)
parser.add_argument('-match_after',
                    type=int, 
                    help='''The number of mismatched bases allowed at the start of 
                    the integrant-end read alignment. Defaults to 2.''',
                    default=2)
parser.add_argument('-tsd',
                    type=int, 
                    help='''The size of the target site duplication. 
                    Defaults to 1. Must be >= 1.''',
                    default=1)
parser.add_argument('--disorg', '-disorg',
                    help='''When set/True, files are not moved to type-specific subdirectories.''',
                    action='store_true')
parser.add_argument('-ltr_umi_offset',
                    type=int, 
                    help='''The number of basepairs between the first basepair of the provided 
                    LTR/integrant sequence and the last basepair of the UMI. Defaults to 0 
                    (i.e., the UMI immediately precedes the given LTR sequence).''',
                    default=0)
parser.add_argument('-ltr_umi_len',
                    type=int, 
                    help='''The length of the LTR/integrant-end UMI. Defaults to 0 (no UMI present).''',
                    default=0)
parser.add_argument('-ltr_umi_pattern',
                    type=str, 
                    help='''Any pattern that defines the LTR/integrant UMI. For example, 4 random bases, followed 
                    by 4 known bases, followed by 4 random bases should be given as NNNNATGCNNNN, 
                    where ATGC is replaced with the known bases in the UMI sequence. 
                    Reads whose UMI does not match the given pattern are removed.''',
                    default=None)
parser.add_argument('-linker_umi_offset',
                    type=int, 
                    help='''The number of basepairs between the first basepair of the provided 
                    linker sequence to the last basepair of the UMI. Defaults to 0  
                    (i.e., the UMI immediately precedes the given linker sequence).''',
                    default=0)
parser.add_argument('-linker_umi_len',
                    type=int, 
                    help='''The length of the linker-end UMI. Defaults to 0 (no UMI present).''',
                    default=0)
parser.add_argument('-linker_umi_pattern',
                    type=str, 
                    help='''Any pattern that defines the linker UMI. For example, 4 random bases, followed 
                    by 4 known bases, followed by 4 random bases should be given as NNNNATGCNNNN, 
                    where ATGC is replaced with the known bases in the UMI sequence. 
                    Reads whose UMI does not match the given pattern are removed.''',
                    default=None)
parser.add_argument('--no_mm', '-no_mm',
                    help='''When set/True, multimapping reads are discarded.''',
                    action='store_true')
parser.add_argument('-min_qual',
                    type=int, 
                    help='''The minimum acceptable average base quality score. 
                    Used to filter out reads with low-quality base calls. 
                    Defaults to 10.''',
                    default=10)
parser.add_argument('-len_diff',
                    type=int, 
                    help='''The maximum allowed length difference on either end of uniquely mapping 
                    fragments for fragments to be grouped together during duplicate removal. Alternatively,
                    the maximum absolute length difference for multimapping fragments. 
                    Defaults to 5.''',
                    default=5)
parser.add_argument('-cluster_win',
                    type=int, 
                    help='''The size of the window used to cluster nearby sites in the final pass. 
                    Defaults to 5.''',
                    default=5)
parser.add_argument('-frag_ratio',
                    type=float, 
                    help='''The ratio of fragment counts used for UMI comparisons. 
                    A match is called if the higher number of counts > (frag_ratio * lower number).
                    Defaults to 2.''',
                    default=2)
parser.add_argument('-genome_fasta',
                    type=str, 
                    help='''The file path to the genome fasta file. 
                    The file must be either bgzip compressed or uncompressed. 
                    Used when ltr_primer is given to look for mispriming.''',
                    default=None)
parser.add_argument('-genome_fasta_index',
                    type=str, 
                    help='''The file path to the genome fasta index file. 
                    This is not strictly necessary if the genome fasta index file is named 
                    <genome_fasta>.fai for an uncompressed genome_fasta file, or 
                    <genome_fasta>.gzi for a bgzip compressed genome_fasta file.''',
                    default=None)
parser.add_argument('--check_mispriming', '-check_mispriming',
                    help='''When set/True, look for mispriming around each mapped IS. 
                    Aligment parameters are currently set internally.''',
                    action='store_true')
parser.add_argument('-misprime_win',
                    type=int, 
                    help='''The one-sided window size in which to check for mispriming.
                    Defaults to 25.''',
                    default=25)
parser.add_argument('-num_perm',
                    type=int, 
                    help='''The number of permutations in the minhash fingerprint. 
                    Defaults to 128. Must be divisble by 8 and >= 32.''',
                    default=128)
parser.add_argument('-seq_sim',
                    type=float,
                    help='''Sequence similarity threshold. Used for validating multimapping read groups and, 
                    in certain instances, assigning multimapping read positions.  
                    Defaults to 0.95. Must be > 0 and <= 1.''',
                    default=0.95)
parser.add_argument('-token_size',
                    type=int, 
                    help='''The token size for MinHash generation. 
                    Defaults to 4 for short-read data and 8 for long-read data.
                    A value of -1 tells the program to use default values.''',
                    default=-1)
parser.add_argument('-hash_similarity',
                    type=float,
                    help='''Defines the similarity threshold between MinHashes. 
                    Used for coarse clustering of multimapping fragments. 
                    Must by >= 0 and <= 1. 
                    By default, internally defined as seq_sim^token_size / (2 - seq_sim^token_size) - 0.05.''',
                    default=-1)
parser.add_argument('-b_bits',
                    type=float,
                    help='''Defines the number of bits with which to represent each MinHash.
                    Must be between 1 and 32. Defaults to 32.''',
                    default=32)
parser.add_argument('-minimizer_win',
                    type=int,
                    help='''Defines the minimizer window size. By default, internally defined as 2 * token_size for long-read sequences 
                    and token_size for short-read sequences. Must be > 0 and <= min_frag_len - token_size + 1. 
                    When None, all k-mers are included in the MinHash.''',
                    default=-1)
parser.add_argument('-min_count',
                    type=int, 
                    help='''The minimum number of mapped sites required to define a particular integration site as abundant. 
                    Used during the final pass to cleanup mapped ISs.   
                    Defaults to 1.''',
                    default=1)
parser.add_argument('-abundant_fc',
                    type=float, 
                    help='''The fold-change threshold between nearby abundant sites for them to be considered 
                    the same. If two nearby abundant sites have abundance fold-change values < abundant_fc, 
                    they are considered different. 
                    Defaults to 2.''',
                    default=2)
parser.add_argument('-low_confidence_fc',
                    type=float, 
                    help='''The fold-change threshold relative to the average number of observations per fragment 
                    for a mapped site to be considered low-confidence. If a site has an abundance fold-change value < 
                    low_confidence_fc-fold from the average number of observations per fragment, the site is removed.    
                    Defaults to 100.''',
                    default=100)
parser.add_argument('--reassign_mm', '-reassign_mm',
                    help='''When set/True, attempt to reassign multimapping reads based on 
                    concordance with uniquely mapping reads or similar multimapping reads.''',
                    action='store_true')
parser.add_argument('-mm_k',
                    type=int, 
                    help='''The size of the k-mers used to reassign multimapping reads.     
                    Defaults to 15. Must be <= min_frag_len - len_diff''',
                    default=15)
parser.add_argument('-mm_group_threshold',
                    type=float, 
                    help='''Defines the lower multimapping group size threshold for whole-group 
                    reassignment to a probable location. 
                    Expressed as a fraction of the total number of multimapping reads.     
                    Defaults to 0.002.''',
                    default=0.002)
parser.add_argument('-um_reassign_diff',
                    type=float, 
                    help='''The fuzzy similarity difference enforced when choosing the best uniquely-mapping fragment 
                    position for multi-mapping fragment reassignment. Used in conjection with um_reassign_fc.
                    Must be >= 0 and < 0.25. Defaults to 0.05.''',
                    default=0.05)
parser.add_argument('-um_reassign_fc',
                    type=float, 
                    help='''Defines the count fold-change required between two uniquely-mapping fragments with similar 
                    sequence similarity scores to a multi-mapping fragment in order to re-define the best match. 
                    Used in conjunction with um_reassign_diff. Must be >= 1. Defaults to 2.''',
                    default=2)
parser.add_argument('--no_dedup', '-no_dedup',
                    help='''When set/True, the pipeline stops after alignment and QC.''',
                    action='store_true')
parser.add_argument('--check_consensus', '-check_consensus',
                    help='''When set/True, reads from input files are sampled to identify
                    common variants of the given LTR and linker sequences. 
                    Results are written to stdout.''',
                    action='store_true')
parser.add_argument('-consensus_sample_size',
                    type=int,
                    help='''The number of reads to sample for consensus checking.
                    Defaults to 10000.''',
                    default=10000)
parser.add_argument('-consensus_threshold',
                    type=float,
                    help='''The fractional threshold for sequence significance. 
                    Used during consensus checking. If the frequency of any sequence 
                    is >= this value, that sequence will be reported.
                    Defaults to 0.01.''',
                    default=0.01)
parser.add_argument('-consensus_error_rate',
                    type=float,
                    help='''The error rate for consensus searching. 
                    Any sequence with <= len(LTR/linker sequence) * consensus_error_rate errors
                    will be reported as a variant provided sufficient representation (see consensus_threshold).
                    Defaults to 0.3.''',
                    default=0.3)
parser.add_argument('--extract_consensus', '-extract_consensus',
                    help='''When set/True, a consensus sequence of length 
                    consensus_length is determined from provided FASTQ files. 
                    Useful for determining integrant/linker sequences when they are unknown/ambiguous.''',
                    action='store_true')
parser.add_argument('-consensus_length',
                    type=int,
                    help='''The length of the consensus sequence to generate. Used with extract_consensus. 
                    Defaults to 100.''',
                    default=100)
parser.add_argument('-consensus_base_threshold',
                    type=float,
                    help='''The threshold required to call a base the consensus. 
                    Positions with base frequency values below this are returned as N. 
                    Defaults to 0.65''',
                    default=0.65)
parser.add_argument('-consensus_cpt_penalty',
                    type=float,
                    help='''The penalty term for changepoint estimation. 
                    Used in defining the estimated consensus sequence. Higher values increase sensitivity, 
                    but also potentially increase noise. 
                    Defaults to 1.5.''',
                    default=1.5)
parser.add_argument('-consensus_peak_threshold',
                    type=float,
                    help='''The fractional threshold relative to the maximum segment mean for a changepoint 
                    segment to be considered part of the consensus.
                    Defaults to 0.9.''',
                    default=0.9)
parser.add_argument('--umi_dedup_fp', '-umi_dedup_fp',
                    help='''When set/True, checks for conflicting UMIs during the final pass. These would be 
                    similar UMIs on fragments mapping to different genomic positions.''',
                    action='store_true')
parser.add_argument('--mle', '-mle',
                    help='''When set/True, site abundance is estimated using maximum likelihood estimation. 
                    This cannot be set when either linker_umi_len or ltr_umi_len > 0 or when 
                    single-end short-read sequencing is being analyzed. 
                    Requires random genome fragmentation.''',
                    action='store_true')
parser.add_argument('-long_read', '--long_read', '-lr', '--lr',
                    help='''When set/True, reads are processed as long-reads (ONT/PB)''',
                    action='store_true')
parser.add_argument('-lr_type',
                    type=str,
                    choices=['map-ont', 'map-pb', 'map-hifi', 'lr:hq'],
                    default='map-ont',
                    help='''The type of long-read sequencing. Fills in the -x value in minimap2.''')
parser.add_argument('-annotations',
                    type=str,
                    nargs="*",
                    default=None,
                    help='''File paths to genomic annotation files (comma-separated). 
                    When not None, ISs overlapping each feature-set and the distance from each IS to the nearest feature 
                    in each feature-set are determined. 
                    Annotation files are assumed to be in BED format (https://github.com/samtools/hts-specs/blob/master/BEDv1.pdf).
                    Nearest distance is determined independently of feature strandedness.''')
parser.add_argument('-write_peaks', '--write_peaks',
                    help='''When set/True, mapped sites are collapsed into peaks and peak ranges are output.''',
                    action='store_true')
parser.add_argument('-stranded_peaks', '--stranded_peaks',
                    help='''When set/True, peaks are called by strand. This should not be set for e.g., AAV integration.''',
                    action='store_true')
parser.add_argument('-peak_win',
                    type=int,
                    help='''Maximum distance (bp) between sites to merge into a single peak.
                    Only used when write_peaks is True.
                    Defaults to 25.''',
                    default=25)
parser.add_argument('-peak_alpha',
                    type=float,
                    help='''Significance threshold for retaining single-strand IS positions
                    in peaks. Expressed as the probability of only observing mapped sites on a given strand. 
                    Sites where this probability is >= peak_alpha are deemed high quality.
                    Only used when write_peaks is True.
                    Defaults to 0.05.''',
                    default=0.05)
parser.add_argument('-remove_chr',
                    type=str, 
                    nargs='*', 
                    help='''The names of chromosomes to remove during mapping.''', 
                    default=None)
parser.add_argument('-bt2_path',
                    type=str, 
                    help='The path to the Bowtie2 executable. OK to ignore for standard installations.',
                    default='bowtie2')
parser.add_argument('-sam_path',
                    type=str, 
                    help='The path to the samtools executable. OK to ignore for standard installations.',
                    default='samtools')
parser.add_argument('-cut_path',
                    type=str, 
                    help='The path to the cutadapt executable. OK to ignore for standard installations.',
                    default='cutadapt')
parser.add_argument('-seqtk_path',
                    type=str, 
                    help='The path to the seqtk executable. OK to ignore for standard installations.',
                    default='seqtk')

args = parser.parse_args()

if __name__ == "__main__":
    if '/' in args.nm:
        parser.error('Sample name cannot contain forward slashes.')
        
    if not args.extract_consensus and args.ltr is None:
        parser.error('ltr must be defined.')
    
    args.r1 = args.ltr_reads
    args.r2 = args.linker_reads
    
    if args.r1 and not args.r2:
        single_end = True
    else:
        single_end = False
        
    if args.long_read and args.token_size == -1:
        args.token_size = 8
    elif args.token_size == -1:
        args.token_size = 4
        
    if args.minimizer_win == -1:
        if args.long_read:
            args.minimizer_win = min(2 * args.token_size, math.floor(args.min_frag_len) - args.token_size + 1)
        else:
            args.minimizer_win = min(args.token_size, math.floor(args.min_frag_len) - args.token_size + 1)
    
    if args.hash_similarity == -1:
        args.hash_similarity = round(max(0, args.seq_sim ** args.token_size / (2 - args.seq_sim ** args.token_size) - 0.05), 3)
        
    if args.annotations:
        args.annotations = [f.strip() for f in args.annotations]

    if args.mle:
        args.len_diff = 0

    curr_dir = os.getcwd()
    processed_dir = os.path.join(curr_dir, 'processed')
    os.makedirs(processed_dir, exist_ok = True)

    if args.cut_path != 'cutadapt':
        align.check_executable(path = args.cut_path, ex_name = 'cutadapt')

    if args.seqtk_path != 'seqtk':
        align.check_executable(path = args.seqtk_path, ex_name = 'seqtk')
    
    if args.check_consensus:
        print('\n')
        print(f'Checking {args.nm} consensus sequences...', flush=True)
        print(f'Integrant-end target sequence: {args.ltr}', flush = True)
        if args.long_read:
            print(f'Linker-end target sequence: {revcomp(args.linker)}', flush = True)
        elif args.r2:
            print(f'Linker-end target sequence: {args.linker}', flush = True)
        print('\n')
        
        check_consensus(
            r1 = args.r1, r2 = args.r2, ltr = args.ltr, linker = args.linker, 
            sample_size = args.consensus_sample_size, consensus_threshold = args.consensus_threshold, 
            consensus_error_rate = args.consensus_error_rate, cut_path = args.cut_path, 
            nthr = args.nthr, processed_directory = processed_dir, long_read = args.long_read, 
            seqtk_path = args.seqtk_path, out_nm = args.nm
        )
        
        print('\n')

        sys.exit()
        
    if args.extract_consensus:
        print('\n')
        print(f'Determining {args.nm} consensus sequences...\n', flush = True)
        print(f'Consensus sequence length: {args.consensus_length} bp', flush = True)
        print(f'Consensus raw base-calling threshold: {args.consensus_base_threshold}', flush = True)
        print(f'Consensus changepoint penalty: {args.consensus_cpt_penalty}', flush = True)
        print(f'Consensus peak threshold: {args.consensus_peak_threshold}', flush = True)
        print('\n')
        
        r1_consensus, r2_consensus = define_consensus(
          r1 = args.r1, 
          r2 = args.r2, 
          consensus_length = args.consensus_length, 
          sample_size = args.consensus_sample_size, 
          base_threshold = args.consensus_base_threshold,
          out_nm = args.nm, 
          seqtk_path = args.seqtk_path, 
          processed_directory = processed_dir, 
          long_read = args.long_read,
          cpt_penalty = args.consensus_cpt_penalty,
          peak_threshold = args.consensus_peak_threshold
        )
        
        print('\n')
        print(f"Raw LTR consensus: {r1_consensus['raw']}")
        print(f"Estimated LTR consensus: {r1_consensus['estimated']}")
        if args.long_read or args.r2:
            print('\n')
            print(f"Raw linker consensus: {r2_consensus['raw']}")
            print(f"Estimated linker consensus: {r2_consensus['estimated']}")
        print('\n')

        sys.exit()
        
    start_time = time.time()
    if (args.linker_umi_len or args.ltr_umi_len) and args.mle:
        parser.error('mle cannot be set while ltr_umi_len and/or linker_umi_len > 0')
    if (single_end and not args.long_read) and args.mle:
        parser.error('mle is incompatible with single-end short-read data.')
    if not single_end and args.long_read:
        parser.error('A linker-end file cannot be given when long_read is True.')
    if not args.g_idx_dir:
        parser.error('g_idx_dir must be defined')
    if not args.g_idx_name:
        parser.error('g_idx_name must be defined')
    # if args.linker is None and (args.long_read or args.r2):
    #     parser.error('A linker sequence must be defined for paired-end and long-read data')
    if args.ltr_primer is None and args.check_mispriming:
        parser.error('ltr_primer must be defined to check for mispriming.')
    if args.check_mispriming and args.genome_fasta is None:
        parser.error('genome_fasta must be defined when misprime_mismatch > -1.')
    if args.v_idx_dir is None:
        parser.error('v_idx_dir must be defined.')
    if args.v_idx_name is None:
        parser.error('v_idx_name must be defined.')
    if args.frag_ratio < 1:
        parser.error('frag_ratio must be >= 1.')
    if args.min_frag_len < 20:
        parser.error('min_frag_len must be >= 20.')
    if args.num_perm % 8 != 0:
        parser.error('num_perm must be a multiple of 8.')
    if args.num_perm < 32:
        parser.error('num_perm must be >= 32.')
    if args.token_size < 3:
        parser.error('token_size must be >= 3.')
    if args.hash_similarity < 0 or args.hash_similarity > 1:
        parser.error(f'hash_similarity must be >= 0 and <= 1.')
    if args.b_bits <= 0 or args.b_bits > 32:
        parser.error('b_bits must be > 0 and <= 32.')
    if args.minimizer_win <= 0 or args.minimizer_win > args.min_frag_len - args.token_size + 1:
        parser.error('minimizer_win must be > 0 and <= min_frag_len - token_size + 1.')
    if args.match_after < 0:
        parser.error('match_after must be >= 0.')
    if args.len_diff > 10 or args.len_diff < 0:
        parser.error('len_diff must be <= 10 and > 0.')
    if args.cluster_win < 0:
        parser.error('cluster_win must be >= 0.')    
    if args.mm_k > (args.min_frag_len - args.len_diff) or args.mm_k < 10:
        parser.error('mm_k must be <= min_frag_len - len_diff and >= 10.')
    if args.low_confidence_fc <= 0:
        parser.error('low_confidence_fc must be > 0')
    if args.min_ttr_len < 10:
        parser.error('min_ttr_len must be >= 10 bp.')
    if args.seq_sim <= 0 or args.seq_sim > 1:
        parser.error('seq_sim must be > 0 and <= 1.')
    if args.mixed and (single_end and not args.long_read):
        parser.error('mixed cannot both be used with single-end short-read data.')
    if args.write_peaks and args.peak_win < 0:
        parser.error('peak_win must be >= 0.')
    if args.tsd < 1:
        parser.error('tsd must be >= 1.')
    if args.um_reassign_diff < 0 or args.um_reassign_diff > 0.25:
        parser.error('um_reassign_diff must be > 0 or <= 0.25.')
    if args.um_reassign_fc < 1:
        parser.error('um_reassign_fc must be >= 1.')
    if args.cap_ttr_error and not args.ttr:
        parser.error('cap_ttr_error cannot be true with ttr is not set.')
        
    if args.genome_fasta:
        genome_compression = check_genome_compression(args.genome_fasta)
        if genome_compression != 'bgzf' and genome_compression != 'uncompressed':
            raise Exception('The given genome fasta file must be uncompressed or bgzip compressed.')

        if not args.genome_fasta_index:
            genome = pysam.FastaFile(filename = args.genome_fasta)
        else:
            if genome_compression == 'bgzf':
                genome = pysam.FastaFile(filename = args.genome_fasta, 
                                         filepath_index_compressed = args.genome_fasta_index)
            elif genome_compression == 'uncompressed':
                genome = pysam.FastaFile(filename = args.genome_fasta, 
                                         filepath_index = args.genome_fasta_index)

    crop.check_crop_input(
      ltr = args.ltr, linker = args.linker, ltr_primer = args.ltr_primer, 
      ltr_error_rate = args.ltr_error_rate, linker_error_rate = args.linker_error_rate, 
      contamination = args.contam
    )
    
    align.check_genome_idx(idx_dir = args.g_idx_dir, idx_name = args.g_idx_name, long_read = args.long_read)
    align.check_genome_idx(idx_dir = args.v_idx_dir, idx_name = args.v_idx_name, long_read = args.long_read)
    
    if args.bt2_path != 'bowtie2':
        align.check_executable(path = args.bt2_path, ex_name = 'bowtie2')
        
    if args.sam_path != 'samtools':
        align.check_executable(path = args.sam_path, ex_name = 'samtools')
        
    if args.mm2_path != 'minimap2':
        align.check_executable(path = args.mm2_path, ex_name = 'minimap2')
      
    if args.cut_path != 'bedtools':
        align.check_executable(path = args.bed_path, ex_name = 'bedtools')
  
    print('\n')
    print(f'Sample name: {args.nm}', flush = True)
    if not single_end:
        print(f'Parsing files {args.r1} and {args.r2}', flush = True)
        print('Mapping type: paired-end', flush = True)
    else:
        print(f'Parsing file {args.r1}', flush = True)
        if args.long_read:
            print('Mapping type: long-read', flush = True)
        else:
            print('Mapping type: single-end', flush = True)
    print(f'Number of threads: {args.nthr}', flush = True)
    print(f'Integrant-end search sequence: {args.ltr}', flush = True)
    if args.ltr2 is not None:
        print(f'Alternative LTR-end search sequence: {args.ltr2}', flush = True)
    print(f'Mixed integrant ends: {args.mixed}')
    print(f'Linker-end search sequence: {args.linker}', flush = True)
    print(f'LTR match error rate {args.ltr_error_rate}', flush = True)
    print(f'Linker match error rate: {args.linker_error_rate}', flush = True)
    
    if args.ttr:
        print(f'Truncated terminal repeats: True', flush = True)
        print(f'Minimum TTR length: {args.min_ttr_len} bp', flush = True)
        if args.cap_ttr_error:
            print(f'Truncated termini errors allowed: {math.floor(args.min_ttr_len * args.ltr_error_rate)}')
    else:
        print(f'Truncated terminal repeats: False', flush = True)
        
    if args.leftmost:
        print(f'Integrant-end match position: leftmost')

    if args.contam is not None:
        print(f"Declared contamination: {', '.join(args.contam)}", flush = True)
        
    if args.remove_chr:
        print(f'Chromosomes to ignore: {args.remove_chr}')
        
    if args.ltr_umi_len > 0:
        print(f'LTR UMI length: {args.ltr_umi_len} bp', flush = True)
        print(f'LTR UMI offset: {args.ltr_umi_offset} bp', flush = True)
        
    if args.ltr_umi_pattern:
        print(f'LTR UMI pattern: {args.ltr_umi_pattern}', flush = True)
        
    if args.linker_umi_len > 0:
        print(f'Linker UMI length: {args.linker_umi_len} bp', flush = True)
        print(f'Linker UMI offset: {args.linker_umi_offset} bp', flush = True)
        
    if args.linker_umi_pattern:
        print(f'Linker UMI pattern: {args.linker_umi_pattern}', flush = True)

    print(f'Minimum fragment length: {args.min_frag_len} bp', flush = True)
    print(f'Maximum fragment length: {args.max_frag_len} bp', flush = True)

    print(f'Allowed integrant read 5\'-end alignment mismatches: {args.match_after} bp', flush = True)
    print(f'Allowed alignment mismatch rate: {args.aln_mismatch_rate}', flush = True)
    print(f'Allowed alignment indel rate: {args.aln_indel_rate}', flush = True)
    print(f'Minimum alignment MAPQ score: {args.min_mapq}')
    print(f'Minimum average base quality score: {args.min_qual}', flush = True)

    if args.no_dedup:
        print(f'Stop after alignment and QC: True', flush = True)
    else:
        if args.U3 is False:
            print('Mapping end: U5', flush = True)
        else:
            print('Mapping end: U3', flush = True)
            
        print(f'TSD width: {args.tsd} bp', flush = True)
        print(f'Fuzzy length difference: {args.len_diff} bp', flush = True)
        print(f'Duplicate count ratio: {args.frag_ratio}', flush = True)

        if args.no_mm is False:
            print('Keep multimapping reads: True', flush = True)
            print(f'Multimapping hash fingerprint length: {args.num_perm}', flush = True)
            print(f'Multimapping token size: {args.token_size}', flush = True)
            print(f'Multimapping b-bits: {args.b_bits}', flush = True)
            print(f'Multimapping minimizer window size: {args.minimizer_win}', flush = True)
            print(f'Multimapping hash similarity threshold: {args.hash_similarity}', flush = True)
            print(f'Multimapping sequence similarity threshold: {args.seq_sim}', flush = True)
            if args.reassign_mm:
                print(f'Multimapping read reassignment: True', flush = True)
                print(f'Multimapping k-mer size: {args.mm_k}', flush = True)
                print(f'Multimapping group size fractional threshold: {args.mm_group_threshold}', flush = True)
                print(f'Reassign similarity difference: {args.um_reassign_diff}')
                print(f'Reassign fold-change: {args.um_reassign_fc}')
            else:
                print(f'Multimapping read reassignment: False', flush = True)
        else:
            print(f'Keep multimapping reads: False', flush = True)
        
        if args.check_mispriming:
            print(f'Look for mispriming: True', flush = True)
            print(f'LTR primer sequence: {args.ltr_primer}', flush = True)
            print(f'Mispriming window size: {args.misprime_win} bp', flush = True)
        else:
            print('Look for mispriming: False', flush = True)
        
        print(f'Minimum site count threshold: {args.min_count}', flush = True)
        print(f'Cluster window size: {args.cluster_win} bp', flush = True)
        print(f'Abundant fold-change: {args.abundant_fc}', flush = True)
        print(f'Low-confidence fold-change: {args.low_confidence_fc}', flush = True)
        
        if args.ltr_umi_len > 0 or args.linker_umi_len > 0:
            if args.umi_dedup_fp:
                print(f'Globally deduplicate UMIs in final pass: True', flush = True)

        if args.mle:
            print(f'Estimate site abundance with MLE: True', flush = True)
        else:
            print(f'Estimate site abundance with MLE: False', flush = True)
            
        if args.write_peaks:
            print('Collapse sites to peaks: True')
            print(f'Peak window size: {args.peak_win} bp')
            print(f'Stranded peaks: {args.stranded_peaks}')
            print(f'Peak alpha: {args.peak_alpha}')
    
    print('\n')
    
    crop_start = time.time()

    with open_file(filename = args.r1, mode = 'rt') as file:
        n_lines = sum(1 for _ in file)
    if n_lines % 4 != 0:
        raise Exception('Number of lines is not a multiple of 4.')
    n_reads = n_lines // 4
        
    print(f'Processing {n_reads} reads...', flush = True)
    print('Cropping LTR and linker sequences...', flush = True)
            
    crop.crop(
      r1 = args.r1, r2 = args.r2, ltr = args.ltr, ltr2 = args.ltr2, 
      linker = args.linker, ltr_error_rate = args.ltr_error_rate, linker_error_rate = args.linker_error_rate, 
      min_frag_len = args.min_frag_len, ltr_umi_len = args.ltr_umi_len, ltr_umi_offset = args.ltr_umi_offset, 
      ltr_umi_pattern = args.ltr_umi_pattern, linker_umi_len = args.linker_umi_len, 
      linker_umi_offset = args.linker_umi_offset, linker_umi_pattern = args.linker_umi_pattern, 
      processed_directory = processed_dir, out_nm = args.nm, nthr = args.nthr, single_end = single_end, 
      long_read = args.long_read, ttr = args.ttr, min_ttr_len = args.min_ttr_len, cut_path = args.cut_path, 
      contam = args.contam, leftmost = args.leftmost, mixed = args.mixed, seqtk_path = args.seqtk_path, 
      cap_ttr_error = args.cap_ttr_error
    )
    
    fq1 = os.path.join(processed_dir, f'{args.nm}_Rltr_cropped.fq.gz')
    if args.r2:
        fq2 = os.path.join(processed_dir, f'{args.nm}_Rlink_cropped.fq.gz')

    with gzip.open(fq1, 'r') as file:
        n_cropped = sum(1 for _ in file) // 4
    
    crop_perc = (n_cropped / n_reads) * 100
    print(f'Number of reads retained after cropping: {n_cropped} ({crop_perc:.2f}%)', flush = True)
    
    crop_end = time.time()
    crop_time = round(crop_end - crop_start, 3)
    print(f'{crop_time} seconds elapsed', flush = True)
    
    if n_cropped == 0:
        print('\n', flush = True)
        print('No reads were retained after cropping. Exiting.', flush = True)
        os.remove(fq1)
        if args.r2:
            os.remove(fq2)
        sys.exit()

    align_start = time.time()
    print('\n', flush = True)
    print('Aligning cropped reads...', flush = True)
                
    if not single_end:
        align.align_pe(
            bt2_path = args.bt2_path, sam_path = args.sam_path, g_idx_dir = args.g_idx_dir, 
            g_idx_name = args.g_idx_name, v_idx_dir = args.v_idx_dir, v_idx_name = args.v_idx_name,
            file1 = fq1, file2 = fq2, out_nm = os.path.join(processed_dir, args.nm), nthr = args.nthr,
            min_frag_len = args.min_frag_len, max_frag_len = args.max_frag_len, aln_seed_len = 22,
            aln_seed_mismatch = 0
        )
    elif not args.long_read:
        align.align_se(
            bt2_path = args.bt2_path, sam_path = args.sam_path, g_idx_dir = args.g_idx_dir, 
            g_idx_name = args.g_idx_name, v_idx_dir = args.v_idx_dir, v_idx_name = args.v_idx_name,
            file1 = fq1, out_nm = os.path.join(processed_dir, args.nm), nthr = args.nthr,
            min_frag_len = args.min_frag_len, max_frag_len = args.max_frag_len, aln_seed_len = 22,
            aln_seed_mismatch = 0
        )
    else:
        align.align_lr(
            mm2_path = args.mm2_path, sam_path = args.sam_path, g_idx_dir = args.g_idx_dir, 
            g_idx_name = args.g_idx_name, file1 = fq1, out_nm = os.path.join(processed_dir, args.nm),  
            nthr = args.nthr, v_idx_dir = args.v_idx_dir, v_idx_name = args.v_idx_name, lr_type = args.lr_type
        )
    
    align_end = time.time()
    align_time = round((align_end - align_start), 3)
    print(f'{align_time} seconds elapsed', flush = True)
    
    process_start = time.time()
    print('\n')
    print('Performing QC on aligned reads...', flush = True)
    
    frags_out = os.path.join(processed_dir, f'{args.nm}_fragments.bed.gz')
    sites_out = os.path.join(processed_dir, f'{args.nm}_sites.bed.gz')
    bc_out = os.path.join(processed_dir, f'{args.nm}_summary.bed.gz')
    uniq_out = os.path.join(processed_dir, f'{args.nm}_sites_unique.bed.gz')
    out_bam = os.path.join(processed_dir, f'{args.nm}_aln.bam')
    out_dup = os.path.join(processed_dir, f'{args.nm}_duplicates.json.gz')
    out_mp = os.path.join(processed_dir, f'{args.nm}_misprimed.fa.gz')
    removed_frags_out = os.path.join(processed_dir, f'{args.nm}_final_pass_removed.bed.gz')
    if args.mle:
        mle_out = os.path.join(processed_dir, f'{args.nm}_sites_unique_mle.bed.gz')
    if args.write_peaks:
        peaks_out = os.path.join(processed_dir, f'{args.nm}_peaks.bed.gz')
    
    print('Parsing bam file...', flush = True)
    reads = process.process_bam(out_bam = out_bam, single_end = single_end, long_read = args.long_read, 
                                remove_chr = args.remove_chr)

    print('Processing aligned reads...', flush = True)
    min_qual = 10 ** (args.min_qual / -10)
    processed_reads = []
    if single_end:
        for read in reads:
            tmp_read = process.process_read(
                read = read, aln_mismatch_rate = args.aln_mismatch_rate, aln_indel_rate = args.aln_indel_rate,
                min_frag_len = args.min_frag_len, max_frag_len = args.max_frag_len, min_mapq = args.min_mapq,
                no_mm = args.no_mm, min_qual = args.min_qual, match_after = args.match_after, single_end = single_end,
                long_read = args.long_read
            )
            processed_reads.append(tmp_read)
        processed_reads = [pp for pp in processed_reads if pp is not None]
    else:
        for read1, read2 in reads:
            tmp_pair = process.process_read_pair(
                read1 = read1, read2 = read2, aln_mismatch_rate = args.aln_mismatch_rate, 
                aln_indel_rate = args.aln_indel_rate, max_frag_len = args.max_frag_len, 
                min_frag_len = args.min_frag_len, min_mapq = args.min_mapq, 
                no_mm = args.no_mm, min_qual = min_qual, match_after = args.match_after,
                single_end = False, long_read = False
            )
            processed_reads.append(tmp_pair)
        processed_reads = [pp for pp in processed_reads if pp[0] is not None and pp[1] is not None]

    n_reads_qc = len(processed_reads)
    reads_qc_perc = (n_reads_qc / len(reads)) * 100
    print(f'Number of reads or pairs that pass QC: {n_reads_qc} ({reads_qc_perc:.2f}%)', flush = True)
    
    process_end = time.time()
    process_time = round((process_end - process_start), 3)
    print(f'{process_time} seconds elapsed', flush = True)

    if args.no_dedup:
        if single_end:
            b2b_cmd1 = f'{args.bed_path} bamtobed -i {out_bam} | gzip > {frags_out}'
            subprocess.call(b2b_cmd1, shell = True, stderr = subprocess.STDOUT)
        else:
            b2b_cmd1 = f'{args.sam_path} sort -@ {args.nthr} -n -O bam {out_bam} | '
            b2b_cmd2 = f'{args.bed_path} bamtobed -bedpe -mate1 -i - | '
            b2b_cmd3 = '''awk 'BEGIN{OFS="\t"} {if($9=="-") print $1,$5,$3,$7,$8,$9; else print $1,$2,$6,$7,$8,$9}' | '''
            b2b_cmd4 = f'sort -k1,1 -k2,2n -k3,3n | gzip > {frags_out}'
            b2b_cmd = b2b_cmd1 + b2b_cmd2 + b2b_cmd3 + b2b_cmd4
            subprocess.call(b2b_cmd, shell = True, stderr = subprocess.STDOUT)
            
        if not args.disorg:
            data_types = ['alignments', 'cropped_reads', 'fragments']
            subdirs = []
            for i in data_types:
                subdir = os.path.join(processed_dir, f'{i}')
                if not os.path.exists(subdir):
                    os.makedirs(subdir)
                subdirs.append(subdir)

            file_mapping = {
                f'{args.nm}_aln.bai': subdirs[0],
                f'{args.nm}_aln.bam': subdirs[0],
                f'{args.nm}_fragments.bed.gz': subdirs[2],
                f'{args.nm}_*_cropped.fq.gz': subdirs[1]
                }
            
            for pattern, target_dir in file_mapping.items():
                for filepath in glob.glob(os.path.join(processed_dir, pattern)):
                    shutil.move(filepath, target_dir)
                    
        end_time = time.time()
        elapsed_time = round((end_time - start_time) / 60, 3)
        print('\n', flush = True)
        print('*** DONE with sample', args.nm, '***', flush = True)
        print(f'Fragments mapped: {n_reads_qc}', flush = True)
        print(f'Total elapsed time: {elapsed_time}', 'minutes', flush = True)
        print('\n', flush = True)

        sys.exit()
    
    if n_reads_qc == 0:
        n_mapped = 0
    else:
        print('\n', flush = True)
        print('Handling duplicate fragments...', flush = True)
        
        frags_dict = {}
        for read_data in processed_reads:
            if not single_end:
                read1_info, read2_info = read_data
            else:
                read1_info = read_data
                read2_info = None
        
            if read1_info['strand'] == '-':
                frag_start = read2_info['reference_start'] if read2_info else read1_info['reference_start']
                frag_end = read1_info['reference_end']
            else:
                frag_start = read1_info['reference_start']
                frag_end = read2_info['reference_end'] if read2_info else read1_info['reference_end']
                
            if read2_info:
                combined_qual = (read1_info['mean_quality'] + read2_info['mean_quality']) / 2
                map_qual = min(read1_info['map_quality'], read2_info['map_quality'])
            else:
                combined_qual = read1_info['mean_quality']
                map_qual = read1_info['map_quality']
            
            frag_dict_entry = {
                'chrom': read1_info['reference_name'],
                'start': frag_start,
                'end': frag_end,
                'count': read1_info['duplicate_count'],
                'strand': read1_info['strand'],
                'ltr_umi': read1_info['ltr_umi'],
                'linker_umi': read1_info['linker_umi'],
                'seq1': read1_info['sequence'],
                'seq2': read2_info['sequence'] if read2_info else None,
                'multi': True if read1_info['multimapping'] else False,
                'mean_qual': -10 * math.log10(combined_qual),
                'map_qual': map_qual,
                'ltr_match': read1_info['ltr_match'],
                'linker_match': read1_info['linker_match'],
                'read_name': read1_info['query_name']
            }
        
            frags_dict[read1_info['query_name']] = frag_dict_entry
        
            
        del frag_dict_entry
        del reads
        del processed_reads
            
        unique_all = {}
        multi_all = {}
        for key, value in frags_dict.items():
            if value['multi']:
                multi_all[key] = value
            else:
                unique_all[key] = value
                
        del frags_dict
        
        n_unique = len(unique_all)
        n_multi = len(multi_all)
        
        if n_unique > 0:
            print(f'Starting number of uniquely mapping fragments: {n_unique}', flush = True)
            uniq_dup_start = time.time()

            unique_all_split = defaultdict(list)
            for read_key, info in unique_all.items():
                key = (info['chrom'], info['strand'])
                value = {
                    'chrom': info['chrom'],
                    'start': info['start'], 
                    'end': info['end'],
                    'count': info['count'],
                    'strand': info['strand'],
                    'ltr_umi': info['ltr_umi'],
                    'linker_umi': info['linker_umi'],
                    'seq1': info['seq1'], 
                    'seq2': info['seq2'],
                    'multi': info['multi'],
                    'mean_qual': info['mean_qual'],
                    'map_qual': info['map_qual'],
                    'ltr_match': info['ltr_match'],
                    'linker_match': info['linker_match'],
                    'read_name': read_key
                }
                
                if key not in unique_all_split:
                    unique_all_split[key] = [value]
                else:
                    unique_all_split[key].append(value)
                    
            del unique_all
            
            print('Collapsing unique exact matches...', flush = True)
            unique_all_split = [
                {key: value} for key, value in sorted(
                    unique_all_split.items(), key = lambda item: len(item[1]), reverse=True
                )
            ]
            
            ue_kept_list = Parallel(n_jobs = min(len(unique_all_split), args.nthr))(
                delayed(clean.unique_exact_matches)(
                    input_dict = unique_all_split[entry]
                )
                for entry in range(len(unique_all_split))
            )
            
            ue_kept_list = [{key: value} for dd in ue_kept_list for key, value in dd.items()]
            
            n_exact_kept = 0
            for entry in ue_kept_list:
                for value in entry.values():
                    n_exact_kept += len(value)
            
            uniq_rm1 = n_unique - n_exact_kept
            uniq_rm1_perc = (uniq_rm1 / n_unique) * 100
            print(f'Number of uniquely mapping reads removed: {uniq_rm1} ({uniq_rm1_perc:.2f}%)', flush = True)

            print('Looking for unique fuzzy matches...', flush = True)
            ue_kept_list = sorted(ue_kept_list, key = lambda x: len(x), reverse = True)
            
            uf_kept_list = Parallel(n_jobs = min(len(ue_kept_list), args.nthr))(
                delayed(clean.unique_fuzzy_matches)(
                    input_dict = ue_kept_list[entry], 
                    len_diff = args.len_diff, 
                    frag_ratio = args.frag_ratio
                ) 
                for entry in range(len(ue_kept_list))
            )
            
            del ue_kept_list

            unique_fuzzy_kept = {}
            unique_fuzzy_dup = {}
            for kept, dup in uf_kept_list:
                unique_fuzzy_kept.update(kept)
                for key, value in dup.items():
                    if key not in unique_fuzzy_dup:
                        unique_fuzzy_dup[key] = value
                    else:
                        unique_fuzzy_dup[key].extend(value)

            del uf_kept_list

            kept_dict = {
                info['read_name']: {
                    key: info[key] for key in [
                        'chrom', 'start', 'end', 'count', 'strand',
                        'ltr_umi', 'linker_umi', 'seq1', 'seq2', 'multi',
                        'mean_qual', 'map_qual', 'ltr_match', 'linker_match', 'read_name'
                    ]
                }
                for info_list in unique_fuzzy_kept.values()
                for info in info_list
            }
            
            del unique_fuzzy_kept
            
            uniq_rm2 = n_exact_kept - len(kept_dict)
            uniq_rm2_perc = (uniq_rm2 / n_unique) * 100
            print(f'Number of additional uniquely mapping reads removed: {uniq_rm2} ({uniq_rm2_perc:.2f}%)',
                    flush = True)
            unique_perc = (len(kept_dict) / n_unique) * 100
            print(f'{len(kept_dict)} uniquely mapping fragments retained ({unique_perc:.2f}%)', 
                    flush = True)
            
            uniq_dup_end = time.time()
            uniq_dup_time = round((uniq_dup_end - uniq_dup_start), 3)
            print(f'{uniq_dup_time} seconds elapsed', flush = True)
            
            dup_dict = unique_fuzzy_dup
            del unique_fuzzy_dup
        else:
            kept_dict = {}
            dup_dict = {}
        
        if n_multi > 0 and not args.no_mm:
            mm_dup_start = time.time()
            print('\n')
            print(f'Starting number of multimapping fragments: {n_multi}', flush = True)
            print('Collapsing multimapping exact matches...', flush = True)
            
            multi_exact_kept = clean.multi_exact_matches(input_dict = multi_all)
            del multi_all
            
            n_multi_exact = len(multi_exact_kept)
            mm_rm1 = n_multi - n_multi_exact
            mm_rm1_perc = (mm_rm1 / n_multi) * 100
            print(f'Number of multimapping mapping reads removed: {mm_rm1} ({mm_rm1_perc:.2f}%)', flush = True)

            print('Hashing multimapping sequences for fuzzy matching...', flush = True)

            multi_exact_hashed = Parallel(n_jobs = args.nthr)(
                delayed(apply_minhash)(
                    key = key, 
                    value = value, 
                    string = (
                        value['seq1'] if value['seq2'] is None or 
                        clean.seq_similarity(value['seq1'], revcomp(value['seq2'])) >= args.seq_sim 
                        else value['seq1'] + value['seq2']
                    ), 
                    num_perm = args.num_perm,
                    token_size = args.token_size,
                    b_bits = args.b_bits,
                    minimizer_win = args.minimizer_win
                ) 
                for key, value in multi_exact_kept.items()
            )

            for key, updated_value in multi_exact_hashed:
                multi_exact_kept[key] = updated_value

            del multi_exact_hashed

            hash_distances, hash_indices = get_nn(
              input_dict = multi_exact_kept, 
              num_perm = args.num_perm,
              nthr = args.nthr,
              b_bits = args.b_bits
            )

            print('Grouping similar hashes...', flush = True)
            mm_solo, mm_groups = group_similar_hashes(
                hash_distances = hash_distances, 
                hash_indices = hash_indices, 
                nthr = args.nthr,
                similarity = args.hash_similarity,
                num_perm = args.num_perm,
                input_dict = multi_exact_kept,
                b_bits = args.b_bits
            )
                
            del hash_distances
            del hash_indices

            mm_grouped_entries = extract_grouped_entries(groups = mm_groups, input_dict = multi_exact_kept)

            items = list(multi_exact_kept.items())
            mm_kept_dict = {items[i][0]: items[i][1] for i in mm_solo}
            
            del mm_solo
            del items

            print('Looking for multimapping fuzzy matches...', flush = True)
            multi_fuzzy_kept, multi_fuzzy_dup = clean.multi_fuzzy_matches(
                groups = mm_grouped_entries,
                frag_ratio = args.frag_ratio,
                nthr = args.nthr,
                seq_sim = args.seq_sim,
                len_diff = args.len_diff,
                min_parallel_size = 500
            )
            
            mm_kept_dict.update(multi_fuzzy_kept)
            dup_dict.update(multi_fuzzy_dup)
            
            mm_rm2 = n_multi_exact - len(mm_kept_dict)
            mm_rm2_perc = (mm_rm2 / n_multi) * 100
            print(f'Number of additional multimapping mapping reads removed: {mm_rm2} ({mm_rm2_perc:.2f}%)', flush = True)
            
            n_mm_kept = len(mm_kept_dict)
            multi_perc = (n_mm_kept / n_multi) * 100
            print(f'{n_mm_kept} multimapping fragments retained ({multi_perc:.2f}%)', flush = True)
            
            if args.reassign_mm:
                print('Reassigning multimapping read positions...', flush = True)
                mm_thresh = max(math.floor(n_mm_kept * args.mm_group_threshold), 1)
                print(f'Multimapping group size threshold for reassignment: {mm_thresh}', flush = True)
                
                verified_kept_dict = clean.verify_mm_positions(
                    mm_kept_dict = mm_kept_dict, 
                    um_kept_dict = kept_dict, 
                    seq_sim = args.seq_sim, 
                    nthr = args.nthr, 
                    len_diff = args.len_diff,
                    k = args.mm_k,
                    min_frag_len = args.min_frag_len,
                    num_perm = args.num_perm,
                    token_size = args.token_size,
                    mm_group_threshold = mm_thresh,
                    threshold = min(0.5, args.hash_similarity),
                    um_reassign_diff = args.um_reassign_diff, 
                    um_reassign_fc = args.um_reassign_fc
                )
                
                if len(verified_kept_dict) != len(mm_kept_dict):
                    raise Exception('Error in reassigning multimapping read positions.')
            else:
                verified_kept_dict = mm_kept_dict

            del multi_exact_kept    
            del multi_fuzzy_kept
            del multi_fuzzy_dup
            del mm_kept_dict
            
            kept_dict.update(verified_kept_dict)
            
            mm_dup_end = time.time()
            mm_dup_time = round((mm_dup_end - mm_dup_start), 3)
            print(f'{mm_dup_time} seconds elapsed', flush = True)
            
            del verified_kept_dict

    if args.check_mispriming:
        mismatch_start = time.time()
        print('\n')
        print('Looking for mispriming...', flush = True)
        shift = args.tsd - 1 if args.U3 else 0
        
        ltr_primer = args.ltr_primer.replace(' ', '').upper()

        n_prior = len(kept_dict)
        n_misprime = 0
        misprime_reads = []
        ps_matrix = parasail.matrix_create("ACGTN", 5, -4)
        for key, value in list(kept_dict.items()):
            if not isinstance(value, dict):
                print(f'key: {key} value: {value}')
            seq = fetch_sequence(
                coordinates = value, 
                genome = genome, 
                U3 = args.U3, 
                shift = shift, 
                misprime_win = args.misprime_win
            )

            if is_misprimed(seq = seq, primer = ltr_primer, matrix = ps_matrix):
                del kept_dict[key]
                misprime_reads.append((key, seq))
                n_misprime += 1
                
        mp_perc = (n_misprime / n_prior) * 100
        print(f'Removing {n_misprime} fragments due to potential mispriming ({mp_perc:.2f}%)', 
                flush = True)
        n_mapped = len(kept_dict)
        mismatch_end = time.time()
        mismatch_time = round((mismatch_end - mismatch_start), 3)
        print(f'{mismatch_time} seconds elapsed', flush = True)
    elif n_reads_qc > 0:
        shift = args.tsd - 1 if args.U3 else 0
        n_mapped = len(kept_dict)
            
    if n_mapped > 0:
        final_start = time.time()
        print('\n')
        print(f'Performing final pass through kept fragments...', flush = True)
        
        kept_dict, removed_dict = final_pass_collapse(
            kept_frags = kept_dict,
            cluster_win = args.cluster_win,
            nthr = args.nthr,
            min_count = args.min_count,
            abundant_fc = args.abundant_fc,
            umi_dedup_fp = args.umi_dedup_fp,
            low_confidence_fc = args.low_confidence_fc
        )
        
        n_mapped_final = len(kept_dict)
        if n_mapped_final == 0:
            raise Exception('No fragments remaining after final pass.')
        
        final_end = time.time()
        final_time = round((final_end - final_start), 3)
        print(f'{final_time} seconds elapsed', flush = True)
        
        uniq_mapped = 0
        for read_name, read in kept_dict.items():
            if not read['multi']:
                uniq_mapped += 1
        
        print('\n')
        print(f'{n_mapped_final} reads retained:', flush = True)
        print(f' {uniq_mapped} uniquely mapping reads ({((uniq_mapped / n_mapped_final) * 100):.2f}%)', flush = True)
        print(f' {n_mapped_final - uniq_mapped} multimapping reads ({(((n_mapped_final - uniq_mapped) / n_mapped_final) * 100):.2f}%)', flush = True)

        kept_dict = sorted(
            kept_dict.items(),
            # key = lambda item: (natural_key(item[1]['chrom']), item[1]['start'], item[1]['end'])
            key = lambda item: (
                natural_key(item[1]['chrom']),
                (item[1]['end'] - shift) - 1 if item[1]['strand'] == '-' else item[1]['start'] + shift
            )
        )
        
        kept_frags = dict(kept_dict)
        
        del kept_dict
        
        if args.mle:
            print('\n')
            print(f'Estimating site abundances using MLE...', flush = True)
            mle_start = time.time()
            mle_estimates = sonic_abundance(
                frag_dict = kept_frags, 
                U3 = args.U3, 
                shift = shift, 
                min_frag_len = args.min_frag_len
            )
            mle_end = time.time()
            mle_time = round((mle_end - mle_start), 3)
            print(f'{mle_time} seconds elapsed', flush = True)

        with (gzip.open(frags_out, 'wt') as frags, gzip.open(sites_out, 'wt') as sites,
              gzip.open(bc_out, 'wt') as bc, gzip.open(removed_frags_out, 'wt') as removed_fp):
            
            bc_cols = ['chrom', 'frag_start', 'frag_end', 'read_name', 'frag_count',
                       'frag_strand', 'multimapping', 'ltr_umi', 'linker_umi',
                       'ltr_match', 'linker_match', 'site_start', 'site_end', 'site_strand']
            bc.write('\t'.join(bc_cols) + '\n')
            removed_fp.write('\t'.join(bc_cols) + '\n')
            
            site_dict = {}
            
            if args.annotations and not args.mle:
                site_chroms, site_starts, site_strands, site_counts = [], [], [], []

            for key, value in kept_frags.items():
                frag_info = [
                    value['chrom'],
                    value['start'],
                    value['end'],
                    key,
                    value['count'],
                    value['strand']
                ]
                
                frags.write('\t'.join(map(str, frag_info)) + '\n')
                
                if value['strand'] == '-':
                    site_start = (value['end'] - shift) - 1
                    site_end = (value['end'] - shift)
                    site_strand = '-' if not args.U3 else '+'
                else:
                    site_start = (value['start'] + shift)
                    site_end = (value['start'] + shift) + 1
                    site_strand = '+' if not args.U3 else '-'
                
                site_info = [
                    value['chrom'],
                    site_start,
                    site_end,
                    key,
                    value['count'],
                    site_strand
                ]

                sites.write('\t'.join(map(str, site_info)) + '\n')
                
                site_dict[key] = {
                    'chrom': site_info[0],
                    'start': site_info[1],
                    'end': site_info[2],
                    'strand': site_info[5]
                }
                
                bc_info = [
                    value['chrom'],
                    value['start'],
                    value['end'],
                    key,
                    value['count'],
                    value['strand'],
                    value['multi'],
                    value['ltr_umi'],
                    value['linker_umi'],
                    value['ltr_match'],
                    value['linker_match'],
                    site_start,
                    site_end,
                    site_strand
                ]
                
                if args.annotations and not args.mle:
                    site_chroms.append(value['chrom']) 
                    site_starts.append(site_start if site_strand == '+' else (site_end - 1))
                    site_strands.append(value['strand'])
                    site_counts.append(value['count'])

                bc.write('\t'.join(map(str, bc_info)) + '\n')
                
            if args.annotations and not args.mle:
                is_coords = pd.DataFrame({
                    "Chromosome": site_chroms,
                    "Start": site_starts,
                    "End": [s + 1 for s in site_starts],
                    "Strand": site_strands,
                    "Count": site_counts
                })

                is_coords = pr.PyRanges(is_coords)
                
                del site_chroms
                del site_starts
                del site_strands
                del site_counts
                
            for key, value in removed_dict.items():
                if value['strand'] == '-':
                    rfp_site_start = (value['end'] - shift) - 1
                    rfp_site_end = (value['end'] - shift)
                    rfp_site_strand = '-' if not args.U3 else '+'
                else:
                    rfp_site_start = (value['start'] + shift)
                    rfp_site_end = (value['start'] + shift) + 1
                    rfp_site_strand = '+' if not args.U3 else '-'

                rfp_info = [
                    value['chrom'],
                    value['start'],
                    value['end'],
                    key,
                    value['count'],
                    value['strand'],
                    value['multi'],
                    value['ltr_umi'],
                    value['linker_umi'],
                    value['ltr_match'],
                    value['linker_match'],
                    rfp_site_start,
                    rfp_site_end,
                    rfp_site_strand
                ]

                removed_fp.write('\t'.join(map(str, rfp_info)) + '\n')
                
        uniq_counts = defaultdict(int)
        for value in site_dict.values():
            item_key = (value['chrom'], value['start'], value['end'], value['strand'])
            uniq_counts[item_key] += 1
        
        collapsed_sites = []
        if not args.mle:
            site_counts = []

        for (chrom, start, end, strand), count in uniq_counts.items():
            collapsed_sites.append({
                'chrom': chrom,
                'start': start,
                'end': end,
                'name': '.',
                'count': count,
                'strand': strand
            })
            
            if not args.mle:
                site_counts.append(count)
                
        if not args.mle:
            diversity = diversity_metrics(site_counts = site_counts)
            diversity_statement = (f"Simpson index: {diversity['simpson']:.4f}")
            del site_counts

        with gzip.open(uniq_out, 'wt') as uniq:
            for value in collapsed_sites:
                collapsed_info = [value['chrom'], value['start'], value['end'],
                                  value['name'], value['count'], value['strand']]
                
                uniq.write('\t'.join(map(str, collapsed_info)) + '\n')
                
        if args.write_peaks:
            all_sites = []
            
            if args.stranded_peaks:
                for site in collapsed_sites:
                    is_coord = site['start'] if site['strand'] == '+' else site['end']
                    all_sites.append({'chrom': site['chrom'], 'start': is_coord,
                                      'end': is_coord if site['strand'] == '-' else (is_coord + 1), 'count': site['count'],
                                      'strand': site['strand'], 'quality': True})
            else:
                is_plus  = defaultdict(int)
                is_minus = defaultdict(int)
                for site in collapsed_sites:
                    is_coord = site['start'] if site['strand'] == '+' else site['end']
                    site_key = (site['chrom'], is_coord)
                    if site['strand'] == '+': 
                        is_plus[site_key]  += site['count']
                    else:
                        is_minus[site_key] += site['count']

                dual_keys = set(is_plus) & set(is_minus)
                total_plus = sum(is_plus[k]  for k in dual_keys)
                total_minus = sum(is_minus[k] for k in dual_keys)
                total = total_plus + total_minus
                if total > 0:
                    plus_prob = total_plus / total
                    se = (plus_prob * (1 - plus_prob) / total) ** 0.5
                    plus_prob = plus_prob if se <= 0.1 else 0.5
                else:
                    plus_prob = 0.5

                all_keys = set(is_plus) | set(is_minus)
                for key in all_keys:
                    chrom, is_coord = key
                    if key in dual_keys:
                        count = is_plus[key] + is_minus[key]
                        strand = '.'
                        quality_site = True
                    else:
                        count = is_plus.get(key, 0) + is_minus.get(key, 0)
                        prob = plus_prob ** count if key in is_plus else (1 - plus_prob) ** count
                        strand = '+' if key in is_plus else '-'
                        quality_site = prob >= args.peak_alpha

                    all_sites.append({'chrom': chrom, 'start': is_coord,
                                      'end': is_coord + 1, 'count': count,
                                      'strand': strand, 'quality': quality_site})

            all_sites.sort(key=lambda x: (natural_key(x['chrom']), x['start']))

            peaks = []
            for site in all_sites:
                if (peaks
                    and site['chrom'] == peaks[-1]['chrom']
                    and site['start'] - peaks[-1]['end'] <= args.peak_win
                    and (not args.stranded_peaks or site['strand'] == peaks[-1]['strand'])):
                    peaks[-1]['end'] = max(peaks[-1]['end'], site['end'])
                    if site['quality']:
                        peaks[-1]['count'] += site['count']
                        peaks[-1]['n_sites'] += 1
                        if not args.stranded_peaks:
                            peaks[-1]['has_plus'] = peaks[-1]['has_plus'] or site['strand'] in ('+', '.')
                            peaks[-1]['has_minus'] = peaks[-1]['has_minus'] or site['strand'] in ('-', '.')
                        if site['count'] > peaks[-1]['apex_count']:
                            peaks[-1]['apex'] = site['start']
                            peaks[-1]['apex_count'] = site['count']
                else:
                    peaks.append({
                        'chrom': site['chrom'],
                        'start': site['start'],
                        'end': site['end'],
                        'strand': site['strand'],
                        'count': site['count'] if site['quality'] else 0,
                        'n_sites': 1 if site['quality'] else 0,
                        'has_plus': site['strand'] in ('+', '.') if site['quality'] else False,
                        'has_minus': site['strand'] in ('-', '.') if site['quality'] else False,
                        'apex': site['start'],
                        'apex_count': site['count'] if site['quality'] else 0
                    })

            written_peaks = []
            with gzip.open(peaks_out, 'wt') as pf:
                for i, peak in enumerate(
                        (p for p in peaks if p['n_sites'] > 2 and (args.stranded_peaks or (p['has_plus'] and p['has_minus']))), 1):
                    peak_info = [peak['chrom'], peak['start'], peak['end'],
                                 f'peak_{i}', peak['count'], peak['strand'] if args.stranded_peaks else '.', peak['apex']]

                    pf.write('\t'.join(map(str, peak_info)) + '\n')
                    written_peaks.append(peak)

            if args.annotations and written_peaks:
                chroms, starts, ends, strands = zip(*((p['chrom'], p['start'], p['end'],
                                                        p['strand'] if args.stranded_peaks else '.')
                                                       for p in written_peaks))
                peak_coords = pr.PyRanges(pd.DataFrame({
                    'Chromosome': chroms,
                    'Start': starts,
                    'End': ends,
                    'Strand': strands
                }))
                print('\n')
                for ff in args.annotations:
                    compare_annotations(
                        sites = peak_coords,
                        features = ff,
                        out_nm = f'{args.nm}_peaks',
                        processed_directory = processed_dir,
                        mle = False,
                        peaks = True
                    )
        
        if args.check_mispriming:        
            with gzip.open(out_mp, 'wt') as mp:
                for entry in misprime_reads:
                    mp.write('>' + entry[0] + '\n' + entry[1] + '\n')
                
        with gzip.open(out_dup, 'wt', encoding = 'utf-8') as dups:
            json.dump(dup_dict, dups, indent = 4)
            
        if args.mle:
            if args.annotations:
                site_chroms, site_starts, site_strands = [], [], []
            site_counts = []

            with gzip.open(mle_out, 'wt') as sa:
                for value in mle_estimates:
                    mle_info = [value['chrom'], value['start'], value['end'],
                                value['name'], value['count'], value['strand']]
                    
                    if args.annotations:
                        site_chroms.append(value['chrom']) 
                        site_starts.append(value['start'] if value['strand'] == '+' else (value['end'] - 1))
                        site_strands.append(value['strand'])
                    site_counts.append(value['count'])
                
                    sa.write('\t'.join(map(str, mle_info)) + '\n')
                    
            if args.annotations:
                is_coords = pd.DataFrame({
                    "Chromosome": site_chroms,
                    "Start": site_starts,
                    "End": [s + 1 for s in site_starts],
                    "Strand": site_strands,
                    "Count": site_counts
                })

                is_coords = pr.PyRanges(is_coords)
                
                del site_chroms
                del site_starts
                del site_strands
            
            diversity = diversity_metrics(site_counts = site_counts)
            diversity_statement = (f"Simpson index: {diversity['simpson']:.4f}")
            del site_counts
                
        if args.annotations:
            print('\n')
            for ff in args.annotations:
                compare_annotations(
                    sites = is_coords, 
                    features = ff, 
                    out_nm = args.nm, 
                    processed_directory = processed_dir,
                    mle = args.mle
                )
    else:
        with (gzip.open(frags_out, 'wt') as frags, gzip.open(sites_out, 'wt') as sites, 
              gzip.open(bc_out, 'wt') as bc, gzip.open(uniq_out, 'wt') as counts,
              gzip.open(out_mp, 'wt') as mp, gzip.open(out_dup, 'wt') as dups):
            pass
        if n_reads_qc == 0:
            print('\n', flush = True)
            print('No quality fragments were retained. No integration sites were mapped.', flush = True)
        else:
            print('\n', flush = True)
            print('No read pairs pass QC. No integration sites were mapped.', flush = True)
            with open(out_bam, 'wt') as frags, open(out_bam.replace('.bam', '.bai')):
                pass
    
    if not args.disorg:
        data_types = ['alignments', 'cropped_reads', 'fragments', 'sites', 'removed']
        if args.annotations:
            data_types.append('comparisons')
        if args.write_peaks:
            data_types.append('peaks')
        subdirs = []
        for i in data_types:
            subdir = os.path.join(processed_dir, f'{i}')
            if not os.path.exists(subdir):
                os.makedirs(subdir)
            subdirs.append(subdir)

        file_mapping = {
            f'{args.nm}_aln.bai': subdirs[0],
            f'{args.nm}_aln.bam': subdirs[0],
            f'{args.nm}_fragments.bed.gz': subdirs[2],
            f'{args.nm}_sites.bed.gz': subdirs[3],
            f'{args.nm}_summary.bed.gz': subdirs[2],
            f'{args.nm}_*_cropped.fq.gz': subdirs[1],
            f'{args.nm}_sites_unique.bed.gz': subdirs[3],
            f'{args.nm}_misprimed.fa.gz': subdirs[4],
            f'{args.nm}_duplicates.json.gz': subdirs[4],
            f'{args.nm}_final_pass_removed.bed.gz': subdirs[4],
            f'{args.nm}_sites_unique_mle.bed.gz': subdirs[3]
            }
        
        if args.annotations:
            file_mapping[f'{args.nm}_*_nearest.bed.gz'] = subdirs[5]
            file_mapping[f'{args.nm}_*_overlap.bed.gz'] = subdirs[5]
            
        if args.write_peaks:
            file_mapping[f'{args.nm}_peaks.bed.gz'] = subdirs[-1]
        
        for pattern, target_dir in file_mapping.items():
            for filepath in glob.glob(os.path.join(processed_dir, pattern)):
                shutil.move(filepath, target_dir)
    
    end_time = time.time()
    elapsed_time = round((end_time - start_time) / 60, 3)
    print('\n', flush = True)
    print('*** DONE with sample', args.nm, '***', flush = True)
    print(f'Sites mapped: {n_mapped_final}', flush = True)
    print(f'{diversity_statement}')
    print(f'Total elapsed time: {elapsed_time}', 'minutes', flush = True)
    print('\n', flush = True)